# Keyboard: map caps-lock to escape.
# input "type:keyboard" {
#     xkb_options caps:escape
# }

# Pointer: lower mouse sensitivity
input type:pointer {
    # accel_profile "flat"
    pointer_accel -0.8
}
